syntax = "proto3";

package proto.worldbase;

option java_multiple_files = true;
option java_outer_classname = "CivilizationMetaProtoOuter";

// Метаданные цивилизации игрового мира
message CivilizationMetaProto {
  int32 version = 1; // номер версии объекта
  string id = 2; // идентификатор цивилизации
  string code_name = 3; // кодовое название цивилизации
  string code_state = 4; // код государства цивилизации
  string code_culture = 5; // код культуры цивилизации
  string flag = 6; // флаг цивилизации
  string color_hex = 7; // hex-цвет цивилизации без альфа-канала
}
