syntax = "proto3";

package proto.common;

option java_multiple_files = true;
option java_outer_classname = "SyncStateResponseProtoOuter";

import "proto/common/sync_state_object_type.proto";
import "proto/syncstate/sync_state_object.proto";

// Мессадж для синхронизации состояния игровой партии на клиенте. Мессадж идет только со стороны сервера
// В ObjectTypeProto тип объекта который хотим синхронизировать
message SyncStateResponseProto {
  proto.common.SyncStateObjectTypeProto type = 1;
  int32 version = 2;
  repeated proto.syncstate.SyncStateObjectProto objects = 3;
}
